kind: pipeline
type: docker
name: ci

steps:
  - name: "Install dependencies"
    image: node:14
    commands:
      - cd ctt-frontend
      - npm ci

  - name: "Lint"
    image: node:14
    commands:
      - cd ctt-frontend
      - "npx ng lint"
    depends_on: ["Install dependencies"]

  - name: "Prettier"
    image: node:14
    commands:
      - cd ctt-frontend
      - "npx prettier --check ."
    depends_on: ["Install dependencies"]

  - name: "Test & Coverage"
    image: buildkite/puppeteer
    commands:
      - cd ctt-frontend
      - "npx ng test --browsers ChromeHeadlessNoSandbox --watch false --progress false --codeCoverage"
    depends_on: ["Install dependencies"]

  ######
  # CD Branch develop
  #####
  - name: "Amplify develop"
    image: node:14
    commands:
      - cd ctt-frontend
      - npm install -g @aws-amplify/cli
      - mkdir ~/.aws
      - echo "[default]" > ~/.aws/credentials
      - echo "aws_access_key_id=$KEYID" >> ~/.aws/credentials
      - echo "aws_secret_access_key=$KEYSECRET" >> ~/.aws/credentials
      - echo "[default]" > ~/.aws/config
      - echo "region=us-east-1" >> ~/.aws/config
      - npx amplify pull --envName dev --yes
    environment:
      KEYID:
        from_secret: aws_access_key_id
      KEYSECRET:
        from_secret: aws_secret_access_key
    when:
      branch:
        - develop
        - 3-aws-deployment
      event:
        - push
    depends_on: ["Test & Coverage", "Lint"]

  - name: "Build develop"
    image: node:14
    commands:
      - cd ctt-frontend
      - npm run build
    depends_on: ["Amplify develop"]

  - name: "Push develop"
    image: plugins/ecr
    settings:
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo: ctt
      registry: 356962203731.dkr.ecr.us-east-1.amazonaws.com
      dockerfile: ctt-frontend/Dockerfile
      tags: ["develop"]
    depends_on: ["Build develop"]
